### PR TITLE
VA and PSIRT fixes

### PR DESCRIPTION
**Pull request by Bhagyashreek8**

### CODE REVIEW

**Review by mssachan — APPROVED** [review]
lgtm

**Review by mssachan — CHANGES_REQUESTED** [review]
Need to use `"fix_version": "1.58.3, 1.57.1, 1.56.3",` for `google.golang.org/grpc`

**Review by mssachan — APPROVED** [review]
LGTM

**Review by ambiknai — APPROVED** [review]

**Review by mssachan — APPROVED** [review]
lgtm

**Pull request merged**
