### PR TITLE
integrate keyprotect root key crn while creating buckets

### PR DESCRIPTION
**Pull request by Bhagyashreek8**

### CODE REVIEW

**Comment by Bhagyashreek8** [comment]
Test results -
Secret structure
```
---
apiVersion: v1
data:
  access-key: xxx
  secret-key: xxx
  kp-customer-root-key-crn: <keyprotect-root-key-crn in base64 encoded format>
kind: Secret
metadata:
  name: satstoragesecretkp
type: ibm/ibmc-s3fs
```
PVC yaml
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bha-pvc-01
  namespace: default
  annotations:
    ibm.io/auto-create-bucket: "false"
    ibm.io/auto-delete-bucket: "false"
    ibm.io/bucket: "abha-kp-01"
    ibm.io/secret-name: "satstoragesecretkp"
    ibm.io/secret-namespace: "default"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ibmc-s3fs-flex-regional
```
PVC created successfully
```
$ kubectl get pvc
NAME         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS              AGE
bha-pvc-01   Bound    pvc-66f8e5ec-7b30-4658-b0b3-b4a4c391b4f7   10Gi       RWO            ibmc-s3fs-flex-regional   104m
```

test logs -
```
I0105 12:00:43.109756       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"bha-pvc-01", UID:"66f8e5ec-7b30-4658-b0b3-b4a4c391b4f7", APIVersion:"v1", ResourceVersion:"27232324", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/bha-pvc-01"
{"level":"info","ts":"2023-01-05T12:00:43.110Z","caller":"provisioner/ibm-s3fs-provisioner.go:454","msg":"bha-pvc-01:cdib6s7d0lkcjp42qru0:Provisioning storage with these spec","requestID":"adba6dc3-c779-468e-92e8-d4902262afd2"}
{"level":"info","ts":"2023-01-05T12:00:43.110Z","caller":"provisioner/ibm-s3fs-provisioner.go:455","msg":"bha-pvc-01:cdib6s7d0lkcjp42qru0:PVC Details: ","requestID":"adba6dc3-c779-468e-92e8-d4902262afd2","pvc":"pvc-66f8e5ec-7b30-4658-b0b3-b4a4c391b4f7"}
{"level":"info","ts":"2023-01-05T12:00:43.110Z","caller":"provisioner/ibm-s3fs-provisioner.go:231","msg":"bha-pvc-01:cdib6s7d0lkcjp42qru0:validate annotations and assign default values to annotations","requestID":"9490ddba-635e-49da-bde6-babc5643b371"}
{"level":"info","ts":"2023-01-05T12:00:43.135Z","caller":"provisioner/ibm-s3fs-provisioner.go:510","msg":"bha-pvc-01:cdib6s7d0lkcjp42qru0 ConfigBucketAccessPolicy: false, SetQuotaLimit: false","requestID":"adba6dc3-c779-468e-92e8-d4902262afd2"}
{"level":"info","ts":"2023-01-05T12:00:43.135Z","caller":"provisioner/ibm-s3fs-provisioner.go:609","msg":"bha-pvc-01:cdib6s7d0lkcjp42qru0 :creating bucket: abha-kp-01","requestID":"adba6dc3-c779-468e-92e8-d4902262afd2"}
{"level":"info","ts":"2023-01-05T12:00:46.351Z","caller":"provisioner/ibm-s3fs-provisioner.go:711","msg":"bha-pvc-01:cdib6s7d0lkcjp42qru0: acccess mode is.. ","requestID":"adba6dc3-c779-468e-92e8-d4902262afd2","access mode":["ReadWriteOnce"]}
I0105 12:00:46.351921       1 controller.go:1439] provision "default/bha-pvc-01" class "ibmc-s3fs-flex-regional": volume "pvc-66f8e5ec-7b30-4658-b0b3-b4a4c391b4f7" provisioned
I0105 12:00:46.351997       1 controller.go:1456] provision "default/bha-pvc-01" class "ibmc-s3fs-flex-regional": succeeded
I0105 12:00:46.352014       1 volume_store.go:212] Trying to save persistentvolume "pvc-66f8e5ec-7b30-4658-b0b3-b4a4c391b4f7"
I0105 12:00:46.385080       1 volume_store.go:219] persistentvolume "pvc-66f8e5ec-7b30-4658-b0b3-b4a4c391b4f7" saved
I0105 12:00:46.385246       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"bha-pvc-01", UID:"66f8e5ec-7b30-4658-b0b3-b4a4c391b4f7", APIVersion:"v1", ResourceVersion:"27232324", FieldPath:""}): type: 'Normal' reason: 'ProvisioningSucceeded' Successfully provisioned volume pvc-66f8e5ec-7b30-4658-b0b3-b4a4c391b4f7
```

Verified creating a bucket with other secret that doesnt have `kp-customer-root-key-crn` entry, that works as usual. (No regression) 

with the kp secret, if you try to create a pvc with any existing bucket, it fails with below error
```
I0105 12:42:59.299678       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"bha-pvc-03", UID:"f33c82cb-08f2-4c08-9ba0-4fc0480635e7", APIVersion:"v1", ResourceVersion:"27245082", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "ibmc-s3fs-flex-regional": bha-pvc-03 : cdib6s7d0lkcjp42qru0 :cannot access bucket amb-csi: NotFound: Not Found
```

**Comment by Bhagyashreek8** [comment]
Screenshot 2023-01-05 at 8 09 21 PM

**Comment by ambiknai** [comment]
@Bhagyashreek8  Adding couple of scenarios that we have to verify

1. To make sure we don't log the encryption key [ both valid and error cases ].
2. KP deletion - usecase1

      1. Create Key Protect Instance with root key
      2. Create Secret  using KP
      3. Create PVC using above secret
      4. Once volume is up -> Delete root Key
      5. Mount a pod to the volume
3.  KP deletion - usecase2
      1. Create Key Protect Instance with root key
      2. Create Secret  using KP
      3. Create PVC using above secret
      4. Once volume is up -> Delete root Key
      5. Create new PVC using same secret and validate the error message
      
      It would be good to document the error messages for troubleshooting for any customer issues.

**Comment by Bhagyashreek8** [comment]
Verification of above mentioned usecases
1. We are not logging the keys in any scenario.

2. create secret with kp-root-key-crn, create pvc.
```
$ kubectl create -f satStorageSecret.yaml 
secret/satstoragesecretkp created
Bhagyashrees-MacBook-Pro-2:keyprotect bhagyashree$ 
Bhagyashrees-MacBook-Pro-2:keyprotect bhagyashree$ 
Bhagyashrees-MacBook-Pro-2:keyprotect bhagyashree$ kubectl create -f kp_pvc.yaml 
persistentvolumeclaim/bha-pvc-01 created
Bhagyashrees-MacBook-Pro-2:keyprotect bhagyashree$ kubectl get pvc
NAME         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS              AGE
bha-pvc-01   Bound    pvc-37793345-1220-47ac-85f5-db2fc5b4926f   10Gi       RWO            ibmc-s3fs-flex-regional   6s
```

Now delete the kp-root-key-crn from the key protect instance.

Now try to create a workload pod using the above PVC. Pod got created but read/write is not happening in the mount path.
```
$ kubectl exec -it test-pod-kp1 -- /bin/bash 
groups: cannot find name for group ID 2000
2000@test-pod-kp1:/$ 
2000@test-pod-kp1:/$ 
2000@test-pod-kp1:/$ df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          98G   71G   22G  77% /
tmpfs            64M     0   64M   0% /dev
tmpfs           7.9G     0  7.9G   0% /sys/fs/cgroup
shm              64M     0   64M   0% /dev/shm
/dev/vda2        98G   71G   22G  77% /etc/hosts
s3fs             16E     0   16E   0% /mnt/cosvol
tmpfs            13G   24K   13G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs           7.9G     0  7.9G   0% /proc/acpi
tmpfs           7.9G     0  7.9G   0% /proc/scsi
tmpfs           7.9G     0  7.9G   0% /sys/firmware
2000@test-pod-kp1:/$ cd /mnt/cosvol/
2000@test-pod-kp1:/mnt/cosvol$ ls
2000@test-pod-kp1:/mnt/cosvol$ vi test.txt
2000@test-pod-kp1:/mnt/cosvol$ echo "Hello" > test.txt
2000@test-pod-kp1:/mnt/cosvol$ ls      
2000@test-pod-kp1:/mnt/cosvol$ touch test.txt
touch: failed to close 'test.txt': No such file or directory
2000@test-pod-kp1:/mnt/cosvol$ 
2000@test-pod-kp1:/mnt/cosvol$ 
2000@test-pod-kp1:/mnt/cosvol$ ls
2000@test-pod-kp1:/mnt/cosvol$ echo "Hello" >> test.txt
2000@test-pod-kp1:/mnt/cosvol$ ls
2000@test-pod-kp1:/mnt/cosvol$         
```

**Comment by Bhagyashreek8** [comment]
Aslo Key Protect support temporary disable/enable of root keys - https://cloud.ibm.com/docs/key-protect?topic=key-protect-disable-keys&interface=ui
When the key is disabled, it behaves as if the key is deleted and no data associated with the key is accessible.

Restoring deleted keys - https://cloud.ibm.com/docs/key-protect?topic=key-protect-restore-keys&interface=ui

**Comment by Bhagyashreek8** [comment]
usecase - create a secret with kp-root-key-crn. Delete the root-key. Create a PVC using this secret.
=> Throws error saying `The KMS key id was not found.`
```
E0106 09:03:18.959865       1 controller.go:964] Giving up syncing claim "062bf82a-4129-48f2-8983-e7301c6be419" because failures 1 >= threshold 1
E0106 09:03:18.959921       1 controller.go:981] error syncing claim "062bf82a-4129-48f2-8983-e7301c6be419": failed to provision volume with StorageClass "ibmc-s3fs-flex-regional": bha-pvc-02:cdib6s7d0lkcjp42qru0 :cannot create bucket abha-kp-4: InvalidRequest: The KMS key id was not found.
	status code: 400, request id: 69309f7a-3ab5-453a-965d-64597b418235, host id: 
I0106 09:03:18.960044       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"bha-pvc-02", UID:"062bf82a-4129-48f2-8983-e7301c6be419", APIVersion:"v1", ResourceVersion:"27609366", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "ibmc-s3fs-flex-regional": bha-pvc-02:cdib6s7d0lkcjp42qru0 :cannot create bucket abha-kp-4: InvalidRequest: The KMS key id was not found.
	status code: 400, request id: 69309f7a-3ab5-453a-965d-64597b418235, host id: 
```

**Comment by Bhagyashreek8** [comment]
usecase - create pvc and pod, and then delete the kp-root-key-crn. Now try to access files and write to files from the mounted pod to the bucket.
=> After deleting the root-key-crn, the behavior of read/write to the bucket was not constant(when tested within 5 mins of root-key deletion). Some times it allowed read/write sometimes it threw error.
```
$ kubectl exec -it test-pod-kp1 -- /bin/bash
groups: cannot find name for group ID 2000
2000@test-pod-kp1:/$ df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          98G   72G   22G  77% /
tmpfs            64M     0   64M   0% /dev
tmpfs           7.9G     0  7.9G   0% /sys/fs/cgroup
shm              64M     0   64M   0% /dev/shm
/dev/vda2        98G   72G   22G  77% /etc/hosts
s3fs             16E     0   16E   0% /mnt/cosvol
tmpfs            13G   24K   13G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs           7.9G     0  7.9G   0% /proc/acpi
tmpfs           7.9G     0  7.9G   0% /proc/scsi
tmpfs           7.9G     0  7.9G   0% /sys/firmware
2000@test-pod-kp1:/$ cd /mnt/cosvol/
2000@test-pod-kp1:/mnt/cosvol$ ls
my.txt	new.txt  test.txt
2000@test-pod-kp1:/mnt/cosvol$ cat my.txt 
cos with kp
new write2
root-key-crn deleted and tring edit
2000@test-pod-kp1:/mnt/cosvol$ cat test.txt 
hello
2000@test-pod-kp1:/mnt/cosvol$ vi test.txt 
E72: Close error on swap file2000@test-pod-kp1:/mnt/cosvol$ cat test.txt 
cat: test.txt: No such file or directory
2000@test-pod-kp1:/mnt/cosvol$ ls
my.txt	new.txt  test.txt
2000@test-pod-kp1:/mnt/cosvol$ cat test.txt 
cat: test.txt: No such file or directory
2000@test-pod-kp1:/mnt/cosvol$ cat new.txt 
new write
2000@test-pod-kp1:/mnt/cosvol$ echo "write2" >> new.txt 
2000@test-pod-kp1:/mnt/cosvol$ cat new.txt 
2000@test-pod-kp1:/mnt/cosvol$ 
2000@test-pod-kp1:/mnt/cosvol$ 
2000@test-pod-kp1:/mnt/cosvol$ ls
my.txt	new.txt  test.txt
2000@test-pod-kp1:/mnt/cosvol$ cat my.txt 

cat: my.txt: No such file or directory
2000@test-pod-kp1:/mnt/cosvol$ 
2000@test-pod-kp1:/mnt/cosvol$ 
2000@test-pod-kp1:/mnt/cosvol$ 
2000@test-pod-kp1:/mnt/cosvol$ cat new.txt 
cat: new.txt: No such file or directory
2000@test-pod-kp1:/mnt/cosvol$ 
2000@test-pod-kp1:/mnt/cosvol$ ls
my.txt	new.txt  test.txt
2000@test-pod-kp1:/mnt/cosvol$ cat my.txt 
cos with kp
new write2
root-key-crn deleted and tring edit
2000@test-pod-kp1:/mnt/cosvol$ cat new.txt 

new write
2000@test-pod-kp1:/mnt/cosvol$ 
```

When tried after 30 mins, read/write access was completely revoked
```
$ kubectl exec -it test-pod-kp1 -- /bin/bash
groups: cannot find name for group ID 2000
2000@test-pod-kp1:/$ cd /mnt/cosvol/
2000@test-pod-kp1:/mnt/cosvol$ 
2000@test-pod-kp1:/mnt/cosvol$ 
2000@test-pod-kp1:/mnt/cosvol$ 
2000@test-pod-kp1:/mnt/cosvol$ 
2000@test-pod-kp1:/mnt/cosvol$ ls
my.txt	new.txt  test.txt
2000@test-pod-kp1:/mnt/cosvol$ cat my.txt 
cat: my.txt: No such file or directory
2000@test-pod-kp1:/mnt/cosvol$ cat new.txt 
cat: new.txt: No such file or directory
2000@test-pod-kp1:/mnt/cosvol$ 
2000@test-pod-kp1:/mnt/cosvol$ cat test.txt 
cat: test.txt: No such file or directory
2000@test-pod-kp1:/mnt/cosvol$ vi my.txt 

E72: Close error on swap file2000@test-pod-kp1:/mnt/cosvol$ 
2000@test-pod-kp1:/mnt/cosvol$ 
2000@test-pod-kp1:/mnt/cosvol$ 
2000@test-pod-kp1:/mnt/cosvol$ touch 30minslater.txt
touch: failed to close '30minslater.txt': No such file or directory
2000@test-pod-kp1:/mnt/cosvol$ 
2000@test-pod-kp1:/mnt/cosvol$ 
2000@test-pod-kp1:/mnt/cosvol$ echo  "try write" >> after30mins.txt
2000@test-pod-kp1:/mnt/cosvol$ ls
my.txt	new.txt  test.txt
2000@test-pod-kp1:/mnt/cosvol$ 
```

**Review by nkkashyap — APPROVED** [review]
LGTM

**Review by ambiknai — APPROVED** [review]

**Pull request merged**
